import React from "react";

function Potrait() {
  return (
   
   <div>
    <p className="paragraph">
      WISH YOU MANY MORE HAPPY RETURNS OF THE DAY MINKI. YOU WILL GET EVERYTHING YOU WANT. YEAH IT'S FAR FROM HOME, HOPE YOU WILL BE
       HAPPY AS ALWAYS. FINALLY JUST SMILE YOU KNOW WHY I AM SAYING THIS. WISH YOU MANY MORE HAPPY RETURNS OF THE DAY MINKI. YOU WILL GET EVERYTHING YOU WANT. YEAH IT'S FAR FROM HOME, HOPE YOU WILL BE
       HAPPY AS ALWAYS. FINALLY JUST SMILE YOU KNOW WHY I AM SAYING THIS. WISH YOU MANY MORE HAPPY RETURNS OF THE DAY MINKI. YOU WILL GET EVERYTHING YOU WANT. YEAH IT'S FAR FROM HOME, HOPE YOU WILL BE
       HAPPY AS ALWAYS. FINALLY JUST SMILE YOU KNOW WHY I AM SAYING THIS. WISH YOU MANY MORE HAPPY RETURNS OF THE DAY MINKI. YOU WILL GET EVERYTHING YOU WANT. YEAH IT'S FAR FROM HOME, HOPE YOU WILL BE
       HAPPY AS ALWAYS. FINALLY JUST SMILE YOU KNOW WHY I AM SAYING THIS. WISH YOU MANY MORE HAPPY RETURNS OF THE DAY MINKI. YOU WILL GET EVERYTHING YOU WANT. YEAH IT'S FAR FROM HOME, HOPE YOU WILL BE
       HAPPY AS ALWAYS. FINALLY JUST SMILE YOU KNOW WHY I AM SAYING THIS. WISH YOU MANY MORE HAPPY RETURNS OF THE DAY MINKI. YOU WILL GET EVERYTHING YOU WANT. YEAH IT'S FAR FROM HOME, HOPE YOU WILL BE
       HAPPY AS ALWAYS. FINALLY JUST SMILE YOU KNOW WHY I AM SAYING THIS. WISH YOU MANY MORE HAPPY RETURNS OF THE DAY MINKI. YOU WILL GET EVERYTHING YOU WANT. YEAH IT'S FAR FROM HOME, HOPE YOU WILL BE
       HAPPY AS ALWAYS. FINALLY JUST SMILE YOU KNOW WHY I AM SAYING THIS. WISH YOU MANY MORE HAPPY RETURNS OF THE DAY MINKI. YOU WILL GET EVERYTHING YOU WANT. YEAH IT'S FAR FROM HOME, HOPE YOU WILL BE
       HAPPY AS ALWAYS. FINALLY JUST SMILE YOU KNOW WHY I AM SAYING THIS. WISH YOU MANY MORE HAPPY RETURNS OF THE DAY MINKI. YOU WILL GET EVERYTHING YOU WANT. YEAH IT'S FAR FROM HOME, HOPE YOU WILL BE
       HAPPY AS ALWAYS. FINALLY JUST SMILE YOU KNOW WHY I AM SAYING THIS. WISH YOU MANY MORE HAPPY RETURNS OF THE DAY MINKI. YOU WILL GET EVERYTHING YOU WANT. YEAH IT'S FAR FROM HOME, HOPE YOU WILL BE
       HAPPY AS ALWAYS. FINALLY JUST SMILE YOU KNOW WHY I AM SAYING THIS. WISH YOU MANY MORE HAPPY RETURNS OF THE DAY MINKI. YOU WILL GET EVERYTHING YOU WANT. YEAH IT'S FAR FROM HOME, HOPE YOU WILL BE
       HAPPY AS ALWAYS. FINALLY JUST SMILE YOU KNOW WHY I AM SAYING THIS. WISH YOU MANY MORE HAPPY RETURNS OF THE DAY MINKI. YOU WILL GET EVERYTHING YOU WANT. YEAH IT'S FAR FROM HOME, HOPE YOU WILL BE
       HAPPY AS ALWAYS. FINALLY JUST SMILE YOU KNOW WHY I AM SAYING THIS. WISH YOU MANY MORE HAPPY RETURNS OF THE DAY MINKI. YOU WILL GET EVERYTHING YOU WANT. YEAH IT'S FAR FROM HOME, HOPE YOU WILL BE
       HAPPY AS ALWAYS. FINALLY JUST SMILE YOU KNOW WHY I AM SAYING THIS. WISH YOU MANY MORE HAPPY RETURNS OF THE DAY MINKI. YOU WILL GET EVERYTHING YOU WANT. YEAH IT'S FAR FROM HOME, HOPE YOU WILL BE
       HAPPY AS ALWAYS. FINALLY JUST SMILE YOU KNOW WHY I AM SAYING THIS. WISH YOU MANY MORE HAPPY RETURNS OF THE DAY MINKI. YOU WILL GET EVERYTHING YOU WANT. YEAH IT'S FAR FROM HOME, HOPE YOU WILL BE
       HAPPY AS ALWAYS. FINALLY JUST SMILE YOU KNOW WHY I AM SAYING THIS. WISH YOU MANY MORE HAPPY RETURNS OF THE DAY MINKI. YOU WILL GET EVERYTHING YOU WANT. YEAH IT'S FAR FROM HOME, HOPE YOU WILL BE
       HAPPY AS ALWAYS. FINALLY JUST SMILE YOU KNOW WHY I AM SAYING THIS. WISH YOU MANY MORE HAPPY RETURNS OF THE DAY MINKI. YOU WILL GET EVERYTHING YOU WANT. YEAH IT'S FAR FROM HOME, HOPE YOU WILL BE
       HAPPY AS ALWAYS. FINALLY JUST SMILE YOU KNOW WHY I AM SAYING THIS. WISH YOU MANY MORE HAPPY RETURNS OF THE DAY MINKI. YOU WILL GET EVERYTHING YOU WANT. YEAH IT'S FAR FROM HOME, HOPE YOU WILL BE
       HAPPY AS ALWAYS. FINALLY JUST SMILE YOU KNOW WHY I AM SAYING THIS. WISH YOU MANY MORE HAPPY RETURNS OF THE DAY MINKI. YOU WILL GET EVERYTHING YOU WANT. YEAH IT'S FAR FROM HOME, HOPE YOU WILL BE
       HAPPY AS ALWAYS. FINALLY JUST SMILE YOU KNOW WHY I AM SAYING THIS. WISH YOU MANY MORE HAPPY RETURNS OF THE DAY MINKI. YOU WILL GET EVERYTHING YOU WANT. YEAH IT'S FAR FROM HOME, HOPE YOU WILL BE
       HAPPY AS ALWAYS. FINALLY JUST SMILE YOU KNOW WHY I AM SAYING THIS. WISH YOU MANY MORE HAPPY RETURNS OF THE DAY MINKI. YOU WILL GET EVERYTHING YOU WANT. YEAH IT'S FAR FROM HOME, HOPE YOU WILL BE
       HAPPY AS ALWAYS. FINALLY JUST SMILE YOU KNOW WHY I AM SAYING THIS. WISH YOU MANY MORE HAPPY RETURNS OF THE DAY MINKI. YOU WILL GET EVERYTHING YOU WANT. YEAH IT'S FAR FROM HOME, HOPE YOU WILL BE
       HAPPY AS ALWAYS. FINALLY JUST SMILE YOU KNOW WHY I AM SAYING THIS. WISH YOU MANY MORE HAPPY RETURNS OF THE DAY MINKI. YOU WILL GET EVERYTHING YOU WANT. YEAH IT'S FAR FROM HOME, HOPE YOU WILL BE
       HAPPY AS ALWAYS. FINALLY JUST SMILE YOU KNOW WHY I AM SAYING THIS. WISH YOU MANY MORE HAPPY RETURNS OF THE DAY MINKI. YOU WILL GET EVERYTHING YOU WANT. YEAH IT'S FAR FROM HOME, HOPE YOU WILL BE
       HAPPY AS ALWAYS. FINALLY JUST SMILE YOU KNOW WHY I AM SAYING THIS. WISH YOU MANY MORE HAPPY RETURNS OF THE DAY MINKI. YOU WILL GET EVERYTHING YOU WANT. YEAH IT'S FAR FROM HOME, HOPE YOU WILL BE
       HAPPY AS ALWAYS. FINALLY JUST SMILE YOU KNOW WHY I AM SAYING THIS. WISH YOU MANY MORE HAPPY RETURNS OF THE DAY MINKI. YOU WILL GET EVERYTHING YOU WANT. YEAH IT'S FAR FROM HOME, HOPE YOU WILL BE
       HAPPY AS ALWAYS. FINALLY JUST SMILE YOU KNOW WHY I AM SAYING THIS. WISH YOU MANY MORE HAPPY RETURNS OF THE DAY MINKI. YOU WILL GET EVERYTHING YOU WANT. YEAH IT'S FAR FROM HOME, HOPE YOU WILL BE
       HAPPY AS ALWAYS. FINALLY JUST SMILE YOU KNOW WHY I AM SAYING THIS. WISH YOU MANY MORE HAPPY RETURNS OF THE DAY MINKI. YOU WILL GET EVERYTHING YOU WANT. YEAH IT'S FAR FROM HOME, HOPE YOU WILL BE
       HAPPY AS ALWAYS. FINALLY JUST SMILE YOU KNOW WHY I AM SAYING THIS. WISH YOU MANY MORE HAPPY RETURNS OF THE DAY MINKI. YOU WILL GET EVERYTHING YOU WANT. YEAH IT'S FAR FROM HOME, HOPE YOU WILL BE
       HAPPY AS ALWAYS. FINALLY JUST SMILE YOU KNOW WHY I AM SAYING THIS. WISH YOU MANY MORE HAPPY RETURNS OF THE DAY MINKI. YOU WILL GET EVERYTHING YOU WANT. YEAH IT'S FAR FROM HOME, HOPE YOU WILL BE
       HAPPY AS ALWAYS. FINALLY JUST SMILE YOU KNOW WHY I AM SAYING THIS. WISH YOU MANY MORE HAPPY RETURNS OF THE DAY MINKI. YOU WILL GET EVERYTHING YOU WANT. YEAH IT'S FAR FROM HOME, HOPE YOU WILL BE
       HAPPY AS ALWAYS. FINALLY JUST SMILE YOU KNOW WHY I AM SAYING THIS. WISH YOU MANY MORE HAPPY RETURNS OF THE DAY MINKI. YOU WILL GET EVERYTHING YOU WANT. YEAH IT'S FAR FROM HOME, HOPE YOU WILL BE
       HAPPY AS ALWAYS. FINALLY JUST SMILE YOU KNOW WHY I AM SAYING THIS. WISH YOU MANY MORE HAPPY RETURNS OF THE DAY MINKI. YOU WILL GET EVERYTHING YOU WANT. YEAH IT'S FAR FROM HOME, HOPE YOU WILL BE
       HAPPY AS ALWAYS. FINALLY JUST SMILE YOU KNOW WHY I AM SAYING THIS. WISH YOU MANY MORE HAPPY RETURNS OF THE DAY MINKI. YOU WILL GET EVERYTHING YOU WANT. YEAH IT'S FAR FROM HOME, HOPE YOU WILL BE
       HAPPY AS ALWAYS. FINALLY JUST SMILE YOU KNOW WHY I AM SAYING THIS. WISH YOU MANY MORE HAPPY RETURNS OF THE DAY MINKI. YOU WILL GET EVERYTHING YOU WANT. YEAH IT'S FAR FROM HOME, HOPE YOU WILL BE
       HAPPY AS ALWAYS. FINALLY JUST SMILE YOU KNOW WHY I AM SAYING THIS. WISH YOU MANY MORE HAPPY RETURNS OF THE DAY MINKI. YOU WILL GET EVERYTHING YOU WANT. YEAH IT'S FAR FROM HOME, HOPE YOU WILL BE
       HAPPY AS ALWAYS. FINALLY JUST SMILE YOU KNOW WHY I AM SAYING THIS. WISH YOU MANY MORE HAPPY RETURNS OF THE DAY MINKI. YOU WILL GET EVERYTHING YOU WANT. YEAH IT'S FAR FROM HOME, HOPE YOU WILL BE
       HAPPY AS ALWAYS. FINALLY JUST SMILE YOU KNOW WHY I AM SAYING THIS. WISH YOU MANY MORE HAPPY RETURNS OF THE DAY MINKI. YOU WILL GET EVERYTHING YOU WANT. YEAH IT'S FAR FROM HOME, HOPE YOU WILL BE
       HAPPY AS ALWAYS. FINALLY JUST SMILE YOU KNOW WHY I AM SAYING THIS. WISH YOU MANY MORE HAPPY RETURNS OF THE DAY MINKI. YOU WILL GET EVERYTHING YOU WANT. YEAH IT'S FAR FROM HOME, HOPE YOU WILL BE
       HAPPY AS ALWAYS. FINALLY JUST SMILE YOU KNOW WHY I AM SAYING THIS. WISH YOU MANY MORE HAPPY RETURNS OF THE DAY MINKI. YOU WILL GET EVERYTHING YOU WANT. YEAH IT'S FAR FROM HOME, HOPE YOU WILL BE
       HAPPY AS ALWAYS. FINALLY JUST SMILE YOU KNOW WHY I AM SAYING THIS. WISH YOU MANY MORE HAPPY RETURNS OF THE DAY MINKI. YOU WILL GET EVERYTHING YOU WANT. YEAH IT'S FAR FROM HOME, HOPE YOU WILL BE
       HAPPY AS ALWAYS. FINALLY JUST SMILE YOU KNOW WHY I AM SAYING THIS. WISH YOU MANY MORE HAPPY RETURNS OF THE DAY MINKI. YOU WILL GET EVERYTHING YOU WANT. YEAH IT'S FAR FROM HOME, HOPE YOU WILL BE
       HAPPY AS ALWAYS. FINALLY JUST SMILE YOU KNOW WHY I AM SAYING THIS. WISH YOU MANY MORE HAPPY RETURNS OF THE DAY MINKI. YOU WILL GET EVERYTHING YOU WANT. YEAH IT'S FAR FROM HOME, HOPE YOU WILL BE
       HAPPY AS ALWAYS. FINALLY JUST SMILE YOU KNOW WHY I AM SAYING THIS. WISH YOU MANY MORE HAPPY RETURNS OF THE DAY MINKI. YOU WILL GET EVERYTHING YOU WANT. YEAH IT'S FAR FROM HOME, HOPE YOU WILL BE
       HAPPY AS ALWAYS. FINALLY JUST SMILE YOU KNOW WHY I AM SAYING THIS. WISH YOU MANY MORE HAPPY RETURNS OF THE DAY MINKI. YOU WILL GET EVERYTHING YOU WANT. YEAH IT'S FAR FROM HOME, HOPE YOU WILL BE
       HAPPY AS ALWAYS. FINALLY JUST SMILE YOU KNOW WHY I AM SAYING THIS. WISH YOU MANY MORE HAPPY RETURNS OF THE DAY MINKI. YOU WILL GET EVERYTHING YOU WANT. YEAH IT'S FAR FROM HOME, HOPE YOU WILL BE
       HAPPY AS ALWAYS. FINALLY JUST SMILE YOU KNOW WHY I AM SAYING THIS. WISH YOU MANY MORE HAPPY RETURNS OF THE DAY MINKI. YOU WILL GET EVERYTHING YOU WANT. YEAH IT'S FAR FROM HOME, HOPE YOU WILL BE
       HAPPY AS ALWAYS. FINALLY JUST SMILE YOU KNOW WHY I AM SAYING THIS. WISH YOU MANY MORE HAPPY RETURNS OF THE DAY MINKI. YOU WILL GET EVERYTHING YOU WANT. YEAH IT'S FAR FROM HOME, HOPE YOU WILL BE
       HAPPY AS ALWAYS. FINALLY JUST SMILE YOU KNOW WHY I AM SAYING THIS. WISH YOU MANY MORE HAPPY RETURNS OF THE DAY MINKI. YOU WILL GET EVERYTHING YOU WANT. YEAH IT'S FAR FROM HOME, HOPE YOU WILL BE
       HAPPY AS ALWAYS. FINALLY JUST SMILE YOU KNOW WHY I AM SAYING THIS. WISH YOU MANY MORE HAPPY RETURNS OF THE DAY MINKI. YOU WILL GET EVERYTHING YOU WANT. YEAH IT'S FAR FROM HOME, HOPE YOU WILL BE
       HAPPY AS ALWAYS. FINALLY JUST SMILE YOU KNOW WHY I AM SAYING THIS. WISH YOU MANY MORE HAPPY RETURNS OF THE DAY MINKI. YOU WILL GET EVERYTHING YOU WANT. YEAH IT'S FAR FROM HOME, HOPE YOU WILL BE
       HAPPY AS ALWAYS. FINALLY JUST SMILE YOU KNOW WHY I AM SAYING THIS. WISH YOU MANY MORE HAPPY RETURNS OF THE DAY MINKI. YOU WILL GET EVERYTHING YOU WANT. YEAH IT'S FAR FROM HOME, HOPE YOU WILL BE
       HAPPY AS ALWAYS. FINALLY JUST SMILE YOU KNOW WHY I AM SAYING THIS. WISH YOU MANY MORE HAPPY RETURNS OF THE DAY MINKI. YOU WILL GET EVERYTHING YOU WANT. YEAH IT'S FAR FROM HOME, HOPE YOU WILL BE
       HAPPY AS ALWAYS. FINALLY JUST SMILE YOU KNOW WHY I AM SAYING THIS. WISH YOU MANY MORE HAPPY RETURNS OF THE DAY MINKI. YOU WILL GET EVERYTHING YOU WANT. YEAH IT'S FAR FROM HOME, HOPE YOU WILL BE
       HAPPY AS ALWAYS. FINALLY JUST SMILE YOU KNOW WHY I AM SAYING THIS. WISH YOU MANY MORE HAPPY RETURNS OF THE DAY MINKI. YOU WILL GET EVERYTHING YOU WANT. YEAH IT'S FAR FROM HOME, HOPE YOU WILL BE
       HAPPY AS ALWAYS. FINALLY JUST SMILE YOU KNOW WHY I AM SAYING THIS. WISH YOU MANY MORE HAPPY RETURNS OF THE DAY MINKI. YOU WILL GET EVERYTHING YOU WANT. YEAH IT'S FAR FROM HOME, HOPE YOU WILL BE
       HAPPY AS ALWAYS. FINALLY JUST SMILE YOU KNOW WHY I AM SAYING THIS. WISH YOU MANY MORE HAPPY RETURNS OF THE DAY MINKI. YOU WILL GET EVERYTHING YOU WANT. YEAH IT'S FAR FROM HOME, HOPE YOU WILL BE
       HAPPY AS ALWAYS. FINALLY JUST SMILE YOU KNOW WHY I AM SAYING THIS. WISH YOU MANY MORE HAPPY RETURNS OF THE DAY MINKI. YOU WILL GET EVERYTHING YOU WANT. YEAH IT'S FAR FROM HOME, HOPE YOU WILL BE
       HAPPY AS ALWAYS. FINALLY JUST SMILE YOU KNOW WHY I AM SAYING THIS. WISH YOU MANY MORE HAPPY RETURNS OF THE DAY MINKI. YOU WILL GET EVERYTHING YOU WANT. YEAH IT'S FAR FROM HOME, HOPE YOU WILL BE
       HAPPY AS ALWAYS. FINALLY JUST SMILE YOU KNOW WHY I AM SAYING THIS. WISH YOU MANY MORE HAPPY RETURNS OF THE DAY MINKI. YOU WILL GET EVERYTHING YOU WANT. YEAH IT'S FAR FROM HOME, HOPE YOU WILL BE
       HAPPY AS ALWAYS. FINALLY JUST SMILE YOU KNOW WHY I AM SAYING THIS. WISH YOU MANY MORE HAPPY RETURNS OF THE DAY MINKI. YOU WILL GET EVERYTHING YOU WANT. YEAH IT'S FAR FROM HOME, HOPE YOU WILL BE
       HAPPY AS ALWAYS. FINALLY JUST SMILE YOU KNOW WHY I AM SAYING THIS. WISH YOU MANY MORE HAPPY RETURNS OF THE DAY MINKI. YOU WILL GET EVERYTHING YOU WANT. YEAH IT'S FAR FROM HOME, HOPE YOU WILL BE
       HAPPY AS ALWAYS. FINALLY JUST SMILE YOU KNOW WHY I AM SAYING THIS. 
    </p>
    </div>
   
  );
} 

export default Potrait;
